apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: csnklsqfx-python 
  janus-idp.io/tekton: csnklsqfx-python
  backstage.io/kubernetes-id: csnklsqfx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: csnklsqfx-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml